site_name: Playlist de Portugol Studio da HM Programming
site_author: Jurandy Soares

theme:
  name: material
  language: pt
  palette:
    primary: green

nav:
  - Início: index.md
  - 0-instalacao.md
  - 1-introducao.md
  - 2-entrada-e-saida-de-dados.md
  - 3-tipos-de-dados-e-variaveis.md
  - 4-operadores-aritmeticos-i.md
  - 5-operadores-aritmeticos-ii.md
  - 6-desvios-condicionais.md
  - 7-operadores-relacionais.md
  - 8-lacos-de-repeticao.md
  - 9-operacoes-logicas.md
  - 10-desvios-condicionais-ii-escolha-caso.md
  - 11-vetores.md
  - 12-matrizes.md
  - 13-funcoes.md
  - 14-bibliotecas.md
  - 15-arquivos.md
  - 16-resolvendo-algoritmos-2-salvando-informacoes.md
  - 17-portugol-studio-pelo-navegador.md
